

def printl(*args,**kwargs):
    print(*args,end='')
def printable(ch):
    if ch.isprintable():
        return ch
    elif ch == '\n':
        return r'\n'
    elif ch == '\n':
        return r'\t'
    elif ch == '\0':
        return r'\0'
    else:
        return '?'


print(';\tgenerated by the script py_gen_ascii')


    
def isdigit(ch):
    return (ord(ch) >= ord('0')) and (ord(ch) <= ord('9'))
def entry(label_name):
    return 'dw {} - .format_table,'.format(label_name)

for i in range(256):
    ch = chr(i)
    do_print = 1
    if ch == '\0':
        printl(entry('.case_nullchar'))
    elif ch == 'd':
        printl(entry('.case_d'))
    elif ch == 'u':
        printl(entry('.case_u'))
    elif ch == 'X':
        printl(entry('.case_upper_x'))
    elif ch == 'c':
        printl(entry('.case_c'))
    elif ch == 'b':
        printl(entry('.case_b'))
    elif ch == 'x':
        printl(entry('.case_x'))
    elif ch == 's':
        printl(entry('.case_s'))
    elif ch == '+':
        printl(entry('.always_print_sign'))
    elif ch == '.':
        printl(entry('.activate_precision'))
    elif ch == '-':
        printl(entry('.left_justify'))
    elif ch == 'l':
        printl(entry('.long_modifier'))
    elif ch == 'h':
        printl(entry('.short_modifier'))
    elif ch == 'o':
        printl(entry('.case_o'))
    elif ch == '#':
        printl(entry('.case_alternate'))
    elif ch == 'f':
        printl(entry('.case_f'))
    elif isdigit(ch):
        printl(entry('.handle_len'))
    else:
        do_print = 0
        printl(entry('.case_invalid'))
    if do_print:
        print(';  {}  \'{}\''.format(hex(i), printable(ch)))
    else:
        print()

